# Generated by Django 2.2 on 2020-06-04 03:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLookupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(max_length=120, null=True, verbose_name='lookup_type')),
                ('enable_flag', models.SmallIntegerField(verbose_name='enable_flag')),
                ('language', models.CharField(max_length=45, verbose_name='language')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='creation_date')),
            ],
            options={
                'verbose_name': 'MyLookupType',
                'verbose_name_plural': 'MyLookupType',
            },
        ),
        migrations.CreateModel(
            name='MyLookupValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_code', models.CharField(max_length=240, null=True, verbose_name='lookup_code')),
                ('language', models.CharField(max_length=45, verbose_name='language')),
                ('lookup_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.MyLookupType', verbose_name='lookup_type_id')),
            ],
            options={
                'verbose_name': 'MyLookupValue',
                'verbose_name_plural': 'MyLookupValue',
            },
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
