# Generated by Django 2.2 on 2020-06-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200604_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylookuptype',
            name='enable_flag',
            field=models.BooleanField(default=True, verbose_name='enable_flag'),
        ),
    ]
