# Generated by Django 2.2 on 2020-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200604_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylookupvalue',
            name='display_sequence',
            field=models.IntegerField(auto_created=True, null=True, verbose_name='data increment'),
        ),
    ]
