# Generated by Django 2.2 on 2020-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_mylookupvalue_display_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylookupvalue',
            name='display_sequence',
            field=models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='data increment'),
        ),
    ]
